### ISSUE TITLE
NetCDF files are written in CDF-1 classic format

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [NOAA-GSL/SENA-c_sw#19]
The current code writes NetCDF output in CDF-1 classic format.  This format limits the size of files to 2GB.  While 2GB files are sufficient for current needs, upcoming scaling of input data will require file sizes beyond 2GB.  Moving to NetCDF4 format will fix this problem.

**Comment by robgpita** [comment]
@christopherwharrop-noaa Thanks for adding this issue.

**Comment by christopherwharrop-noaa** [comment]
This was fixed in #20
